### ISSUE TITLE
Metrics for number of issues/PR comments per user

### ISSUE THREAD

**Issue by marina-chibizova** [ActionsDesk/github-org-repo-metrics-action#1]
### Is your feature request related to a problem? Please describe.

First of all thank you so much for this action! I have not implemented it yet, but it seems to be a perfect solution for github project management. Just want to check if it's possible to add a feature, that would help us greatly.

### Describe the solution you'd like

Metrics for a number of issue comments per user. PR comments are not so needed, but would be nice.

### Describe alternatives you've considered

We also consider this action https://metrics.lecoq.io/, but it shows static metrics, not dynamic.

**Comment by nicklegan** [comment]
👋 @marina-chibizova 

We currently have a [private beta](https://docs.github.com/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/managing-dormant-users) for enterprise cloud customers where you would be able to download a report with dormant users. Please contact your GitHub Account Manager for more info.
